version: "2"

vars:
  DOCKER_REGISTRY_ACCOUNT: skurtzemann
  DOCKER_IMAGE: morgue
  DOCKER_IMAGE_TAG: {sh: cat VERSION}
  DOCKER_IMAGE_FQDN: "{{.DOCKER_REGISTRY_ACCOUNT}}/{{.DOCKER_IMAGE}}:{{.DOCKER_IMAGE_TAG}}"

tasks:
  "name":
    silent: true
    desc: Display docker image name
    cmds:
      - cmd: echo {{.DOCKER_IMAGE_FQDN}}

  "build":
    desc: Build docker image
    cmds:
      - cmd: |
          docker build \
          -t {{.DOCKER_IMAGE_FQDN}} \
          .

  "push":
    desc: Push image to registry
    cmds:
      - cmd: |
          docker push {{.DOCKER_IMAGE_FQDN}}